import api from './index.js'

export const getWorkspaceToday = () => api.get('/workspace/today')
export const getWorkspaceState = () => api.get('/workspace/state')
export const listWorkspaceEvents = (params = {}) => api.get('/workspace/events', params)
export const applyWorkspaceOp = (payload) => api.post('/workspace/ops', payload)
export const rollbackWorkspaceEvent = (id) => api.post(`/workspace/events/${id}/rollback`)
export const getWorkspaceInsights = (params = {}) => api.get('/workspace/insights', params)
export const listQuickCaptures = (params = {}) => api.get('/workspace/captures', params)
export const createQuickCapture = (payload) => api.post('/workspace/captures', payload)
export const updateQuickCapture = (id, payload) => api.put(`/workspace/captures/${id}`, payload)
export const batchUpdateQuickCaptures = (payload) => api.put('/workspace/captures/batch', payload)
export const linkQuickCapture = (id, payload) => api.post(`/workspace/captures/${id}/link`, payload)
export const getReviewEntry = (params = {}) => api.get('/workspace/reviews', params)
export const saveReviewEntry = (payload) => api.post('/workspace/reviews', payload)
export const listWorkspaceMemories = (params = {}) => api.get('/workspace/memories', params)
export const createWorkspaceMemory = (payload) => api.post('/workspace/memories', payload)
export const updateWorkspaceMemory = (id, payload) => api.put(`/workspace/memories/${id}`, payload)
export const deleteWorkspaceMemory = (id) => api.delete(`/workspace/memories/${id}`)
export const listWorkspaceDecisions = (params = {}) => api.get('/workspace/decisions', params)
export const createWorkspaceDecision = (payload) => api.post('/workspace/decisions', payload)
export const updateWorkspaceDecision = (id, payload) => api.put(`/workspace/decisions/${id}`, payload)
export const chatWithMascotAssistant = (payload) => api.post('/workspace/assistant/chat', payload)
export const listAiProviders = () => api.get('/workspace/ai-providers')
export const listAiProviderModels = (payload) => api.post('/workspace/ai-providers/models', payload)
export const saveAiProvider = (payload) => api.post('/workspace/ai-providers', payload)
export const updateAiProvider = (id, payload) => api.put(`/workspace/ai-providers/${id}`, payload)
export const deleteAiProvider = (id) => api.delete(`/workspace/ai-providers/${id}`)
export const testAiProvider = (id) => api.post(`/workspace/ai-providers/${id}/test`)
export const listWorkspacePets = () => api.get('/workspace/pets')
export const importWorkspacePetPack = (formData) => api.post('/workspace/pets/import', formData)
export const updateWorkspacePetSetting = (payload) => api.put('/workspace/pets/settings', payload)
export const activateWorkspacePet = (id) => api.post(`/workspace/pets/${id}/activate`)
export const deleteWorkspacePet = (id) => api.delete(`/workspace/pets/${id}`)
